# Generated by Django 3.2.6 on 2021-08-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='csrfmiddlewaretoken',
            field=models.CharField(default='Greenday123*', max_length=500),
        ),
    ]
