# Generated by Django 3.2.6 on 2021-08-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_myuser_csrfmiddlewaretoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='csrfmiddlewaretoken',
        ),
    ]
