# Generated by Django 3.0.8 on 2020-09-16 08:12

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('price', models.FloatField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, default='../media/sewing.png', null=True, upload_to='gallery')),
                ('isDiscounted', models.BooleanField(default=False)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('isRemote', models.BooleanField(default=False)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('needCertificate', models.BooleanField(default=False)),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('thumbnail', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='gallery')),
                ('isIntermediate', models.BooleanField(default=False)),
                ('isBeginner', models.BooleanField(default=False)),
                ('isAdvanced', models.BooleanField(default=False)),
            ],
        ),
    ]
