# Generated by Django 3.0.8 on 2020-07-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='isDiscounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='isRemote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='needCertificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
