# Generated by Django 3.0.8 on 2020-07-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200715_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dateFin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
