# Generated by Django 3.0.8 on 2020-07-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(default='../media/sewing.jpg', upload_to='post_images'),
        ),
    ]
