# Generated by Django 3.0.8 on 2020-07-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200716_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(default='../media/sewing.jpg', upload_to=''),
        ),
    ]
