# Generated by Django 3.0.8 on 2020-07-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200716_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(default='../leika_project/media/sewing.jpg', upload_to='post_images'),
        ),
    ]
