# Generated by Django 3.0.8 on 2020-07-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200716_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(default='../media/leika_project/sewing.png', upload_to='gallery'),
        ),
    ]
