# Generated by Django 3.0.8 on 2020-07-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200717_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='imgName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(default='../media/sewing.png', upload_to='gallery'),
        ),
    ]
