# Generated by Django 3.0.8 on 2020-07-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200717_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='imgName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
