# Generated by Django 3.0.8 on 2020-07-19 08:41

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200719_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
