# Generated by Django 3.0.8 on 2020-07-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20200719_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='imgName',
            field=models.URLField(blank=True, null=True),
        ),
    ]
