# Generated by Django 3.0.8 on 2020-07-23 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level', to='courses.Level'),
        ),
    ]
