# Generated by Django 3.0.8 on 2020-07-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20200723_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.AddField(
            model_name='course',
            name='isAdvanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='isBeginner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='isIntermediate',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
