# Generated by Django 3.0.8 on 2020-08-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20200820_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='img',
        ),
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
    ]
