# Generated by Django 3.0.8 on 2020-08-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20200820_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='img',
        ),
        migrations.RemoveField(
            model_name='course',
            name='imgName',
        ),
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
    ]
