# Generated by Django 3.0.8 on 2020-08-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20200820_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
    ]
