# Generated by Django 3.0.8 on 2020-08-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_course_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
    ]
