# Generated by Django 3.0.8 on 2020-09-14 19:29

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_remove_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
