services:
  db:
    image: postgres:14.13
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=Poussin14*
      - POSTGRES_USER=postgres
      - POSTGRES_DB=leika_bdd
    volumes:
      - ./data/db:/var/lib/postgresql/data/

  redis:
    image: redis:6.2
    ports:
      - '6379:6379'
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]
    volumes:
      - redis-data:/data

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./front:/leika/front
    depends_on:
      - backend

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PASSWORD=Poussin14*
      - DB_USER=postgres
      - DB_NAME=leika_bdd
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '8000:8000'
    volumes:
      - ./back:/leika/back
    depends_on:
      - db
      - redis

volumes:
  redis-data:
