# Generated by Django 3.2.6 on 2021-08-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'arts_plastiques'), (2, 'arts_de_scene'), (3, 'loisirs_creatifs'), (4, 'professionnel'), (5, 'culinaire'), (6, 'culture'), (7, 'linguistique'), (8, 'sport'), (9, 'jeux'), (10, 'beaute_bien_etre'), (11, 'tours_circuits')], null=True),
        ),
    ]
